sudo: required
dist: trusty # (14.04)
# xenial (16.04) is not supported yet

language: cpp
compiler:
  - clang

git:
  depth: 1
  
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "T59EnuG2Kptl4T+t8pNTqnRehnLmp7XnNgdic3oI8ElvTPxHFUYnQlW0PjRU7tafF5bNTGuR7sHUr0pNpFjU6FLqDRyrFabeE+hjcmeQFnYDix9BMMSJsKqzab46t7oEp8NnSuGQvCS1izkHa5vnLM6hRXCeilo1ziJlmb8qNlNR6PvhoKUVsH3xRKCsJqzYO1YNUw+faJBdEuHaMzC3rMKsNXI95djCsQSzxLCQEyLDpL3qgGhCdriZGiw27fJ3LsO2XqU+HHh4a+rq1iV4SDqKxDAPp9NYtM9iP0M9ErfyeBHQGhQTc70rq+rMJWiqb10p5iE/NsC3y2WdllgrHtSC5o+R0/H/NN0TUFu4YV4iH0HdM+qImZ4PQi7m1ii3Ny9DfQ4HIJzepeSxl7CFEs8I8a/RzXA9nC907jo/1QadzxaK1sh3KJAFMRodJgUKJo02LbiWIzQyPkPSS9Iay952BO8KwuzLOTH8OoNVXzL+uvzc/2qgPEa9PGhjaXybY0WLJEvLNKlzmJ0EsdYFeP/KvDW75BLm+LYcpKom/PH67AB+utNg/t9HRd5CNEdGDKHVmHLniTP+hNxLN7n/MQp1vaIuSFtdKg3hcerxTIKQMf+FnRQVLIH2FfzFSqR2R4sT3YtDxt2CdMYou6FP9mpifIQigvjM35yHEm6euk0="

addons:
  coverity_scan:
    project:
      name: "azerothcore/azerothcore-wotlk"
      description: "MMORPG Framework"
    notification_email: azerothcore.org@gmail.com
    build_command_prepend: "mkdir build;cd build;cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=1 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=1 -DSERVERS=1 -DWITH_PERFTOOLS=1 -DENABLE_EXTRA_LOGS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=check_install"
    build_command:   "make -j 8 -k"
    branch_pattern: coverity

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get -y install build-essential libtool make cmake cmake-data openssl libgoogle-perftools-dev
  - sudo apt-get -y install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libace-dev
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql;'
  # bin directory already exists in the repo and therefore is not created here
  - cd bin
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=1 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=1 -DSERVERS=1 -DWITH_PERFTOOLS=1 -DENABLE_EXTRA_LOGS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - mysql -uroot < data/sql/create/create_mysql.sql
  - cat data/sql/base/db_auth/*.sql | mysql -uacore -pacore auth
  - cat data/sql/base/db_characters/*.sql | mysql -uacore -pacore characters
  - cat data/sql/base/db_world/*.sql | mysql -uacore -pacore world
  - cat data/sql/updates/db_auth/*.sql | mysql -uacore -pacore auth
  - cat data/sql/updates/db_characters/*.sql | mysql -uacore -pacore characters
  - cat data/sql/updates/db_world/*.sql | mysql -uacore -pacore world
  - cat data/sql/updates/pending_db_auth/*.sql | mysql -uacore -pacore auth
  - cat data/sql/updates/pending_db_characters/*.sql | mysql -uacore -pacore characters
  - cat data/sql/updates/pending_db_world/*.sql | mysql -uacore -pacore world
  - mysql -uroot < data/sql/create/drop_mysql.sql
  - cd bin
  - make -j 8 -k && make install
  - cd check_install/bin
